version: "3.7"

services:
  grpc_image_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "server/server.py"]
    environment:
      - PORT=22222
      - GOOGLY_EYE_PATH=/app/server/googly_eye_tr.png
    networks:
      image_service_mesh:
        aliases:
          - grpc_image_service
    expose:
      - "22222"

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "client/client.py"]
    environment:
      - PORT=5000
      - GRPC_SERVER=grpc_image_service:22222
    networks:
      image_service_mesh:
        aliases:
          - client
    ports:
      - "5000:5000"

networks:
  image_service_mesh: {}
